	<div class="login">
		<form method="post">
			<p style="color:#ddd">Username</p> <input name="myusername" type="text" id="myusername" placeholder="Username" />
			<p style="color:#ddd">Password</p> <input name="mypassword" type="password" id="mypassword" placeholder="password" />
			<input type="submit" name="Submit" value="Login" />
		</form>
		<!--form method="post">
			<p style="color:#ddd">Password</p> <input name="mypassword" type="password" id="mypassword" placeholder="password" />
			<input type="submit" name="Submit" value="Generate" />
		</form-->
	</div>